name: dart_axum_tokio_sever
description: 
version: 0.0.1
publish_to: none
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter_rust_bridge:
    path: vendor/flutter_rust_bridge/frb_dart
  flutter_rust_bridge_utils:
    path: vendor/flutter_rust_bridge/frb_utils
  freezed_annotation: ^2.2.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.4
  freezed: ^2.1.0+1
  build_runner: ^2.4.4
  ffigen: ^8.0.0
