[package]
name = "hello_world_axum_server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
clap = { version = "4.5.1", features = ["derive"] }
lazy_static = "1.4.0"
serde_json = "1.0.113"
simd-json = "0.13.8"
tokio = { version="1.36.0", features=[  "rt-multi-thread",]}
